window.esdocSearchIndex = [
  [
    "aureooms-js-measure/src/0-core/2-derived/counter.js~counter",
    "class/src/0-core/2-derived/Counter.js~Counter.html",
    "<span>Counter</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/0-core/2-derived/Counter.js</span>",
    "class"
  ],
  [
    "aureooms-js-measure/src/0-core/1-monoids/integeradd.js~integeradd",
    "class/src/0-core/1-monoids/IntegerAdd.js~IntegerAdd.html",
    "<span>IntegerAdd</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/0-core/1-monoids/IntegerAdd.js</span>",
    "class"
  ],
  [
    "aureooms-js-measure/src/0-core/1-monoids/integermax.js~integermax",
    "class/src/0-core/1-monoids/IntegerMax.js~IntegerMax.html",
    "<span>IntegerMax</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/0-core/1-monoids/IntegerMax.js</span>",
    "class"
  ],
  [
    "aureooms-js-measure/src/0-core/1-monoids/integermul.js~integermul",
    "class/src/0-core/1-monoids/IntegerMul.js~IntegerMul.html",
    "<span>IntegerMul</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/0-core/1-monoids/IntegerMul.js</span>",
    "class"
  ],
  [
    "aureooms-js-measure/src/0-core/2-derived/interval.js~interval",
    "class/src/0-core/2-derived/Interval.js~Interval.html",
    "<span>Interval</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/0-core/2-derived/Interval.js</span>",
    "class"
  ],
  [
    "aureooms-js-measure/src/0-core/2-derived/keylen.js~keylen",
    "class/src/0-core/2-derived/KeyLen.js~KeyLen.html",
    "<span>KeyLen</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/0-core/2-derived/KeyLen.js</span>",
    "class"
  ],
  [
    "aureooms-js-measure/src/0-core/2-derived/keymeasure.js~keymeasure",
    "class/src/0-core/2-derived/KeyMeasure.js~KeyMeasure.html",
    "<span>KeyMeasure</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/0-core/2-derived/KeyMeasure.js</span>",
    "class"
  ],
  [
    "aureooms-js-measure/src/0-core/1-monoids/keymonoid.js~keymonoid",
    "class/src/0-core/1-monoids/KeyMonoid.js~KeyMonoid.html",
    "<span>KeyMonoid</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/0-core/1-monoids/KeyMonoid.js</span>",
    "class"
  ],
  [
    "aureooms-js-measure/src/0-core/2-derived/max.js~max",
    "class/src/0-core/2-derived/Max.js~Max.html",
    "<span>Max</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/0-core/2-derived/Max.js</span>",
    "class"
  ],
  [
    "aureooms-js-measure/src/0-core/0-base/measure.js~measure",
    "class/src/0-core/0-base/Measure.js~Measure.html",
    "<span>Measure</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/0-core/0-base/Measure.js</span>",
    "class"
  ],
  [
    "aureooms-js-measure/src/1-api/1-measures.js~measures",
    "variable/index.html#static-variable-Measures",
    "<span>Measures</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/1-api/1-Measures.js</span>",
    "variable"
  ],
  [
    "aureooms-js-measure/src/1-api/0-monoids.js~monoids",
    "variable/index.html#static-variable-Monoids",
    "<span>Monoids</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/1-api/0-Monoids.js</span>",
    "variable"
  ],
  [
    "aureooms-js-measure/src/0-core/1-monoids/keymonoid.js~nokey",
    "variable/index.html#static-variable-NoKey",
    "<span>NoKey</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/0-core/1-monoids/KeyMonoid.js</span>",
    "variable"
  ],
  [
    "aureooms-js-measure/src/0-core/1-monoids/product.js~product",
    "class/src/0-core/1-monoids/Product.js~Product.html",
    "<span>Product</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/0-core/1-monoids/Product.js</span>",
    "class"
  ],
  [
    "aureooms-js-measure/src/0-core/1-monoids/product.js~product",
    "function/index.html#static-function-product",
    "<span>product</span> <span class=\"search-result-import-path\">aureooms-js-measure/src/0-core/1-monoids/Product.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/0-core/0-base/measure.js",
    "file/src/0-core/0-base/Measure.js.html",
    "src/0-core/0-base/Measure.js",
    "file"
  ],
  [
    "src/0-core/0-base/measure.js~measure#constructor",
    "class/src/0-core/0-base/Measure.js~Measure.html#instance-constructor-constructor",
    "src/0-core/0-base/Measure.js~Measure#constructor",
    "method"
  ],
  [
    "src/0-core/0-base/measure.js~measure#measure",
    "class/src/0-core/0-base/Measure.js~Measure.html#instance-method-measure",
    "src/0-core/0-base/Measure.js~Measure#measure",
    "method"
  ],
  [
    "src/0-core/0-base/measure.js~measure#monoid",
    "class/src/0-core/0-base/Measure.js~Measure.html#instance-member-monoid",
    "src/0-core/0-base/Measure.js~Measure#monoid",
    "member"
  ],
  [
    "src/0-core/0-base/measure.js~measure#plus",
    "class/src/0-core/0-base/Measure.js~Measure.html#instance-method-plus",
    "src/0-core/0-base/Measure.js~Measure#plus",
    "method"
  ],
  [
    "src/0-core/0-base/measure.js~measure#zero",
    "class/src/0-core/0-base/Measure.js~Measure.html#instance-method-zero",
    "src/0-core/0-base/Measure.js~Measure#zero",
    "method"
  ],
  [
    "src/0-core/0-base/index.js",
    "file/src/0-core/0-base/index.js.html",
    "src/0-core/0-base/index.js",
    "file"
  ],
  [
    "src/0-core/1-monoids/integeradd.js",
    "file/src/0-core/1-monoids/IntegerAdd.js.html",
    "src/0-core/1-monoids/IntegerAdd.js",
    "file"
  ],
  [
    "src/0-core/1-monoids/integeradd.js~integeradd#plus",
    "class/src/0-core/1-monoids/IntegerAdd.js~IntegerAdd.html#instance-method-plus",
    "src/0-core/1-monoids/IntegerAdd.js~IntegerAdd#plus",
    "method"
  ],
  [
    "src/0-core/1-monoids/integeradd.js~integeradd#zero",
    "class/src/0-core/1-monoids/IntegerAdd.js~IntegerAdd.html#instance-method-zero",
    "src/0-core/1-monoids/IntegerAdd.js~IntegerAdd#zero",
    "method"
  ],
  [
    "src/0-core/1-monoids/integermax.js",
    "file/src/0-core/1-monoids/IntegerMax.js.html",
    "src/0-core/1-monoids/IntegerMax.js",
    "file"
  ],
  [
    "src/0-core/1-monoids/integermax.js~integermax#plus",
    "class/src/0-core/1-monoids/IntegerMax.js~IntegerMax.html#instance-method-plus",
    "src/0-core/1-monoids/IntegerMax.js~IntegerMax#plus",
    "method"
  ],
  [
    "src/0-core/1-monoids/integermax.js~integermax#zero",
    "class/src/0-core/1-monoids/IntegerMax.js~IntegerMax.html#instance-method-zero",
    "src/0-core/1-monoids/IntegerMax.js~IntegerMax#zero",
    "method"
  ],
  [
    "src/0-core/1-monoids/integermul.js",
    "file/src/0-core/1-monoids/IntegerMul.js.html",
    "src/0-core/1-monoids/IntegerMul.js",
    "file"
  ],
  [
    "src/0-core/1-monoids/integermul.js~integermul#plus",
    "class/src/0-core/1-monoids/IntegerMul.js~IntegerMul.html#instance-method-plus",
    "src/0-core/1-monoids/IntegerMul.js~IntegerMul#plus",
    "method"
  ],
  [
    "src/0-core/1-monoids/integermul.js~integermul#zero",
    "class/src/0-core/1-monoids/IntegerMul.js~IntegerMul.html#instance-method-zero",
    "src/0-core/1-monoids/IntegerMul.js~IntegerMul#zero",
    "method"
  ],
  [
    "src/0-core/1-monoids/keymonoid.js",
    "file/src/0-core/1-monoids/KeyMonoid.js.html",
    "src/0-core/1-monoids/KeyMonoid.js",
    "file"
  ],
  [
    "src/0-core/1-monoids/keymonoid.js~keymonoid#plus",
    "class/src/0-core/1-monoids/KeyMonoid.js~KeyMonoid.html#instance-method-plus",
    "src/0-core/1-monoids/KeyMonoid.js~KeyMonoid#plus",
    "method"
  ],
  [
    "src/0-core/1-monoids/keymonoid.js~keymonoid#zero",
    "class/src/0-core/1-monoids/KeyMonoid.js~KeyMonoid.html#instance-method-zero",
    "src/0-core/1-monoids/KeyMonoid.js~KeyMonoid#zero",
    "method"
  ],
  [
    "src/0-core/1-monoids/product.js",
    "file/src/0-core/1-monoids/Product.js.html",
    "src/0-core/1-monoids/Product.js",
    "file"
  ],
  [
    "src/0-core/1-monoids/product.js~product#a",
    "class/src/0-core/1-monoids/Product.js~Product.html#instance-member-a",
    "src/0-core/1-monoids/Product.js~Product#a",
    "member"
  ],
  [
    "src/0-core/1-monoids/product.js~product#b",
    "class/src/0-core/1-monoids/Product.js~Product.html#instance-member-b",
    "src/0-core/1-monoids/Product.js~Product#b",
    "member"
  ],
  [
    "src/0-core/1-monoids/product.js~product#constructor",
    "class/src/0-core/1-monoids/Product.js~Product.html#instance-constructor-constructor",
    "src/0-core/1-monoids/Product.js~Product#constructor",
    "method"
  ],
  [
    "src/0-core/1-monoids/product.js~product#plus",
    "class/src/0-core/1-monoids/Product.js~Product.html#instance-method-plus",
    "src/0-core/1-monoids/Product.js~Product#plus",
    "method"
  ],
  [
    "src/0-core/1-monoids/product.js~product#zero",
    "class/src/0-core/1-monoids/Product.js~Product.html#instance-method-zero",
    "src/0-core/1-monoids/Product.js~Product#zero",
    "method"
  ],
  [
    "src/0-core/1-monoids/index.js",
    "file/src/0-core/1-monoids/index.js.html",
    "src/0-core/1-monoids/index.js",
    "file"
  ],
  [
    "src/0-core/2-derived/counter.js",
    "file/src/0-core/2-derived/Counter.js.html",
    "src/0-core/2-derived/Counter.js",
    "file"
  ],
  [
    "src/0-core/2-derived/counter.js~counter#constructor",
    "class/src/0-core/2-derived/Counter.js~Counter.html#instance-constructor-constructor",
    "src/0-core/2-derived/Counter.js~Counter#constructor",
    "method"
  ],
  [
    "src/0-core/2-derived/counter.js~counter#measure",
    "class/src/0-core/2-derived/Counter.js~Counter.html#instance-method-measure",
    "src/0-core/2-derived/Counter.js~Counter#measure",
    "method"
  ],
  [
    "src/0-core/2-derived/interval.js",
    "file/src/0-core/2-derived/Interval.js.html",
    "src/0-core/2-derived/Interval.js",
    "file"
  ],
  [
    "src/0-core/2-derived/interval.js~interval#constructor",
    "class/src/0-core/2-derived/Interval.js~Interval.html#instance-constructor-constructor",
    "src/0-core/2-derived/Interval.js~Interval#constructor",
    "method"
  ],
  [
    "src/0-core/2-derived/interval.js~interval#measure",
    "class/src/0-core/2-derived/Interval.js~Interval.html#instance-method-measure",
    "src/0-core/2-derived/Interval.js~Interval#measure",
    "method"
  ],
  [
    "src/0-core/2-derived/keylen.js",
    "file/src/0-core/2-derived/KeyLen.js.html",
    "src/0-core/2-derived/KeyLen.js",
    "file"
  ],
  [
    "src/0-core/2-derived/keylen.js~keylen#constructor",
    "class/src/0-core/2-derived/KeyLen.js~KeyLen.html#instance-constructor-constructor",
    "src/0-core/2-derived/KeyLen.js~KeyLen#constructor",
    "method"
  ],
  [
    "src/0-core/2-derived/keylen.js~keylen#measure",
    "class/src/0-core/2-derived/KeyLen.js~KeyLen.html#instance-method-measure",
    "src/0-core/2-derived/KeyLen.js~KeyLen#measure",
    "method"
  ],
  [
    "src/0-core/2-derived/keymeasure.js",
    "file/src/0-core/2-derived/KeyMeasure.js.html",
    "src/0-core/2-derived/KeyMeasure.js",
    "file"
  ],
  [
    "src/0-core/2-derived/keymeasure.js~keymeasure#constructor",
    "class/src/0-core/2-derived/KeyMeasure.js~KeyMeasure.html#instance-constructor-constructor",
    "src/0-core/2-derived/KeyMeasure.js~KeyMeasure#constructor",
    "method"
  ],
  [
    "src/0-core/2-derived/keymeasure.js~keymeasure#measure",
    "class/src/0-core/2-derived/KeyMeasure.js~KeyMeasure.html#instance-method-measure",
    "src/0-core/2-derived/KeyMeasure.js~KeyMeasure#measure",
    "method"
  ],
  [
    "src/0-core/2-derived/max.js",
    "file/src/0-core/2-derived/Max.js.html",
    "src/0-core/2-derived/Max.js",
    "file"
  ],
  [
    "src/0-core/2-derived/max.js~max#constructor",
    "class/src/0-core/2-derived/Max.js~Max.html#instance-constructor-constructor",
    "src/0-core/2-derived/Max.js~Max#constructor",
    "method"
  ],
  [
    "src/0-core/2-derived/max.js~max#measure",
    "class/src/0-core/2-derived/Max.js~Max.html#instance-method-measure",
    "src/0-core/2-derived/Max.js~Max#measure",
    "method"
  ],
  [
    "src/0-core/2-derived/index.js",
    "file/src/0-core/2-derived/index.js.html",
    "src/0-core/2-derived/index.js",
    "file"
  ],
  [
    "src/0-core/index.js",
    "file/src/0-core/index.js.html",
    "src/0-core/index.js",
    "file"
  ],
  [
    "src/1-api/0-monoids.js",
    "file/src/1-api/0-Monoids.js.html",
    "src/1-api/0-Monoids.js",
    "file"
  ],
  [
    "src/1-api/1-measures.js",
    "file/src/1-api/1-Measures.js.html",
    "src/1-api/1-Measures.js",
    "file"
  ],
  [
    "src/1-api/index.js",
    "file/src/1-api/index.js.html",
    "src/1-api/index.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ]
]