window.esdocSearchIndex = [
  [
    "@functional-abstraction/measure/src/0-core/2-derived/counter.js~counter",
    "class/src/0-core/2-derived/Counter.js~Counter.html",
    "<span>Counter</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/0-core/2-derived/Counter.js</span>",
    "class"
  ],
  [
    "@functional-abstraction/measure/src/0-core/1-monoids/integeradd.js~integeradd",
    "class/src/0-core/1-monoids/IntegerAdd.js~IntegerAdd.html",
    "<span>IntegerAdd</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/0-core/1-monoids/IntegerAdd.js</span>",
    "class"
  ],
  [
    "@functional-abstraction/measure/src/0-core/1-monoids/integermax.js~integermax",
    "class/src/0-core/1-monoids/IntegerMax.js~IntegerMax.html",
    "<span>IntegerMax</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/0-core/1-monoids/IntegerMax.js</span>",
    "class"
  ],
  [
    "@functional-abstraction/measure/src/0-core/1-monoids/integermul.js~integermul",
    "class/src/0-core/1-monoids/IntegerMul.js~IntegerMul.html",
    "<span>IntegerMul</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/0-core/1-monoids/IntegerMul.js</span>",
    "class"
  ],
  [
    "@functional-abstraction/measure/src/0-core/2-derived/interval.js~interval",
    "class/src/0-core/2-derived/Interval.js~Interval.html",
    "<span>Interval</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/0-core/2-derived/Interval.js</span>",
    "class"
  ],
  [
    "@functional-abstraction/measure/src/0-core/2-derived/keylen.js~keylen",
    "class/src/0-core/2-derived/KeyLen.js~KeyLen.html",
    "<span>KeyLen</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/0-core/2-derived/KeyLen.js</span>",
    "class"
  ],
  [
    "@functional-abstraction/measure/src/0-core/2-derived/keymeasure.js~keymeasure",
    "class/src/0-core/2-derived/KeyMeasure.js~KeyMeasure.html",
    "<span>KeyMeasure</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/0-core/2-derived/KeyMeasure.js</span>",
    "class"
  ],
  [
    "@functional-abstraction/measure/src/0-core/1-monoids/keymonoid.js~keymonoid",
    "class/src/0-core/1-monoids/KeyMonoid.js~KeyMonoid.html",
    "<span>KeyMonoid</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/0-core/1-monoids/KeyMonoid.js</span>",
    "class"
  ],
  [
    "@functional-abstraction/measure/src/0-core/2-derived/max.js~max",
    "class/src/0-core/2-derived/Max.js~Max.html",
    "<span>Max</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/0-core/2-derived/Max.js</span>",
    "class"
  ],
  [
    "@functional-abstraction/measure/src/0-core/0-base/measure.js~measure",
    "class/src/0-core/0-base/Measure.js~Measure.html",
    "<span>Measure</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/0-core/0-base/Measure.js</span>",
    "class"
  ],
  [
    "@functional-abstraction/measure/src/1-api/1-measures.js~measures",
    "variable/index.html#static-variable-Measures",
    "<span>Measures</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/1-api/1-Measures.js</span>",
    "variable"
  ],
  [
    "@functional-abstraction/measure/src/1-api/0-monoids.js~monoids",
    "variable/index.html#static-variable-Monoids",
    "<span>Monoids</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/1-api/0-Monoids.js</span>",
    "variable"
  ],
  [
    "@functional-abstraction/measure/src/0-core/1-monoids/keymonoid.js~nokey",
    "variable/index.html#static-variable-NoKey",
    "<span>NoKey</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/0-core/1-monoids/KeyMonoid.js</span>",
    "variable"
  ],
  [
    "@functional-abstraction/measure/src/0-core/1-monoids/product.js~product",
    "class/src/0-core/1-monoids/Product.js~Product.html",
    "<span>Product</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/0-core/1-monoids/Product.js</span>",
    "class"
  ],
  [
    "@functional-abstraction/measure/src/0-core/1-monoids/product.js~product",
    "function/index.html#static-function-product",
    "<span>product</span> <span class=\"search-result-import-path\">@functional-abstraction/measure/src/0-core/1-monoids/Product.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/0-core/0-base/measure.js",
    "file/src/0-core/0-base/Measure.js.html",
    "src/0-core/0-base/Measure.js",
    "file"
  ],
  [
    "src/0-core/0-base/measure.js~measure#constructor",
    "class/src/0-core/0-base/Measure.js~Measure.html#instance-constructor-constructor",
    "src/0-core/0-base/Measure.js~Measure#constructor",
    "method"
  ],
  [
    "src/0-core/0-base/measure.js~measure#measure",
    "class/src/0-core/0-base/Measure.js~Measure.html#instance-method-measure",
    "src/0-core/0-base/Measure.js~Measure#measure",
    "method"
  ],
  [
    "src/0-core/0-base/measure.js~measure#monoid",
    "class/src/0-core/0-base/Measure.js~Measure.html#instance-member-monoid",
    "src/0-core/0-base/Measure.js~Measure#monoid",
    "member"
  ],
  [
    "src/0-core/0-base/measure.js~measure#plus",
    "class/src/0-core/0-base/Measure.js~Measure.html#instance-method-plus",
    "src/0-core/0-base/Measure.js~Measure#plus",
    "method"
  ],
  [
    "src/0-core/0-base/measure.js~measure#zero",
    "class/src/0-core/0-base/Measure.js~Measure.html#instance-method-zero",
    "src/0-core/0-base/Measure.js~Measure#zero",
    "method"
  ],
  [
    "src/0-core/0-base/index.js",
    "file/src/0-core/0-base/index.js.html",
    "src/0-core/0-base/index.js",
    "file"
  ],
  [
    "src/0-core/1-monoids/integeradd.js",
    "file/src/0-core/1-monoids/IntegerAdd.js.html",
    "src/0-core/1-monoids/IntegerAdd.js",
    "file"
  ],
  [
    "src/0-core/1-monoids/integeradd.js~integeradd#plus",
    "class/src/0-core/1-monoids/IntegerAdd.js~IntegerAdd.html#instance-method-plus",
    "src/0-core/1-monoids/IntegerAdd.js~IntegerAdd#plus",
    "method"
  ],
  [
    "src/0-core/1-monoids/integeradd.js~integeradd#zero",
    "class/src/0-core/1-monoids/IntegerAdd.js~IntegerAdd.html#instance-method-zero",
    "src/0-core/1-monoids/IntegerAdd.js~IntegerAdd#zero",
    "method"
  ],
  [
    "src/0-core/1-monoids/integermax.js",
    "file/src/0-core/1-monoids/IntegerMax.js.html",
    "src/0-core/1-monoids/IntegerMax.js",
    "file"
  ],
  [
    "src/0-core/1-monoids/integermax.js~integermax#plus",
    "class/src/0-core/1-monoids/IntegerMax.js~IntegerMax.html#instance-method-plus",
    "src/0-core/1-monoids/IntegerMax.js~IntegerMax#plus",
    "method"
  ],
  [
    "src/0-core/1-monoids/integermax.js~integermax#zero",
    "class/src/0-core/1-monoids/IntegerMax.js~IntegerMax.html#instance-method-zero",
    "src/0-core/1-monoids/IntegerMax.js~IntegerMax#zero",
    "method"
  ],
  [
    "src/0-core/1-monoids/integermul.js",
    "file/src/0-core/1-monoids/IntegerMul.js.html",
    "src/0-core/1-monoids/IntegerMul.js",
    "file"
  ],
  [
    "src/0-core/1-monoids/integermul.js~integermul#plus",
    "class/src/0-core/1-monoids/IntegerMul.js~IntegerMul.html#instance-method-plus",
    "src/0-core/1-monoids/IntegerMul.js~IntegerMul#plus",
    "method"
  ],
  [
    "src/0-core/1-monoids/integermul.js~integermul#zero",
    "class/src/0-core/1-monoids/IntegerMul.js~IntegerMul.html#instance-method-zero",
    "src/0-core/1-monoids/IntegerMul.js~IntegerMul#zero",
    "method"
  ],
  [
    "src/0-core/1-monoids/keymonoid.js",
    "file/src/0-core/1-monoids/KeyMonoid.js.html",
    "src/0-core/1-monoids/KeyMonoid.js",
    "file"
  ],
  [
    "src/0-core/1-monoids/keymonoid.js~keymonoid#plus",
    "class/src/0-core/1-monoids/KeyMonoid.js~KeyMonoid.html#instance-method-plus",
    "src/0-core/1-monoids/KeyMonoid.js~KeyMonoid#plus",
    "method"
  ],
  [
    "src/0-core/1-monoids/keymonoid.js~keymonoid#zero",
    "class/src/0-core/1-monoids/KeyMonoid.js~KeyMonoid.html#instance-method-zero",
    "src/0-core/1-monoids/KeyMonoid.js~KeyMonoid#zero",
    "method"
  ],
  [
    "src/0-core/1-monoids/product.js",
    "file/src/0-core/1-monoids/Product.js.html",
    "src/0-core/1-monoids/Product.js",
    "file"
  ],
  [
    "src/0-core/1-monoids/product.js~product#a",
    "class/src/0-core/1-monoids/Product.js~Product.html#instance-member-a",
    "src/0-core/1-monoids/Product.js~Product#a",
    "member"
  ],
  [
    "src/0-core/1-monoids/product.js~product#b",
    "class/src/0-core/1-monoids/Product.js~Product.html#instance-member-b",
    "src/0-core/1-monoids/Product.js~Product#b",
    "member"
  ],
  [
    "src/0-core/1-monoids/product.js~product#constructor",
    "class/src/0-core/1-monoids/Product.js~Product.html#instance-constructor-constructor",
    "src/0-core/1-monoids/Product.js~Product#constructor",
    "method"
  ],
  [
    "src/0-core/1-monoids/product.js~product#plus",
    "class/src/0-core/1-monoids/Product.js~Product.html#instance-method-plus",
    "src/0-core/1-monoids/Product.js~Product#plus",
    "method"
  ],
  [
    "src/0-core/1-monoids/product.js~product#zero",
    "class/src/0-core/1-monoids/Product.js~Product.html#instance-method-zero",
    "src/0-core/1-monoids/Product.js~Product#zero",
    "method"
  ],
  [
    "src/0-core/1-monoids/index.js",
    "file/src/0-core/1-monoids/index.js.html",
    "src/0-core/1-monoids/index.js",
    "file"
  ],
  [
    "src/0-core/2-derived/counter.js",
    "file/src/0-core/2-derived/Counter.js.html",
    "src/0-core/2-derived/Counter.js",
    "file"
  ],
  [
    "src/0-core/2-derived/counter.js~counter#constructor",
    "class/src/0-core/2-derived/Counter.js~Counter.html#instance-constructor-constructor",
    "src/0-core/2-derived/Counter.js~Counter#constructor",
    "method"
  ],
  [
    "src/0-core/2-derived/counter.js~counter#measure",
    "class/src/0-core/2-derived/Counter.js~Counter.html#instance-method-measure",
    "src/0-core/2-derived/Counter.js~Counter#measure",
    "method"
  ],
  [
    "src/0-core/2-derived/interval.js",
    "file/src/0-core/2-derived/Interval.js.html",
    "src/0-core/2-derived/Interval.js",
    "file"
  ],
  [
    "src/0-core/2-derived/interval.js~interval#constructor",
    "class/src/0-core/2-derived/Interval.js~Interval.html#instance-constructor-constructor",
    "src/0-core/2-derived/Interval.js~Interval#constructor",
    "method"
  ],
  [
    "src/0-core/2-derived/interval.js~interval#measure",
    "class/src/0-core/2-derived/Interval.js~Interval.html#instance-method-measure",
    "src/0-core/2-derived/Interval.js~Interval#measure",
    "method"
  ],
  [
    "src/0-core/2-derived/keylen.js",
    "file/src/0-core/2-derived/KeyLen.js.html",
    "src/0-core/2-derived/KeyLen.js",
    "file"
  ],
  [
    "src/0-core/2-derived/keylen.js~keylen#constructor",
    "class/src/0-core/2-derived/KeyLen.js~KeyLen.html#instance-constructor-constructor",
    "src/0-core/2-derived/KeyLen.js~KeyLen#constructor",
    "method"
  ],
  [
    "src/0-core/2-derived/keylen.js~keylen#measure",
    "class/src/0-core/2-derived/KeyLen.js~KeyLen.html#instance-method-measure",
    "src/0-core/2-derived/KeyLen.js~KeyLen#measure",
    "method"
  ],
  [
    "src/0-core/2-derived/keymeasure.js",
    "file/src/0-core/2-derived/KeyMeasure.js.html",
    "src/0-core/2-derived/KeyMeasure.js",
    "file"
  ],
  [
    "src/0-core/2-derived/keymeasure.js~keymeasure#constructor",
    "class/src/0-core/2-derived/KeyMeasure.js~KeyMeasure.html#instance-constructor-constructor",
    "src/0-core/2-derived/KeyMeasure.js~KeyMeasure#constructor",
    "method"
  ],
  [
    "src/0-core/2-derived/keymeasure.js~keymeasure#measure",
    "class/src/0-core/2-derived/KeyMeasure.js~KeyMeasure.html#instance-method-measure",
    "src/0-core/2-derived/KeyMeasure.js~KeyMeasure#measure",
    "method"
  ],
  [
    "src/0-core/2-derived/max.js",
    "file/src/0-core/2-derived/Max.js.html",
    "src/0-core/2-derived/Max.js",
    "file"
  ],
  [
    "src/0-core/2-derived/max.js~max#constructor",
    "class/src/0-core/2-derived/Max.js~Max.html#instance-constructor-constructor",
    "src/0-core/2-derived/Max.js~Max#constructor",
    "method"
  ],
  [
    "src/0-core/2-derived/max.js~max#measure",
    "class/src/0-core/2-derived/Max.js~Max.html#instance-method-measure",
    "src/0-core/2-derived/Max.js~Max#measure",
    "method"
  ],
  [
    "src/0-core/2-derived/index.js",
    "file/src/0-core/2-derived/index.js.html",
    "src/0-core/2-derived/index.js",
    "file"
  ],
  [
    "src/0-core/index.js",
    "file/src/0-core/index.js.html",
    "src/0-core/index.js",
    "file"
  ],
  [
    "src/1-api/0-monoids.js",
    "file/src/1-api/0-Monoids.js.html",
    "src/1-api/0-Monoids.js",
    "file"
  ],
  [
    "src/1-api/1-measures.js",
    "file/src/1-api/1-Measures.js.html",
    "src/1-api/1-Measures.js",
    "file"
  ],
  [
    "src/1-api/index.js",
    "file/src/1-api/index.js.html",
    "src/1-api/index.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ]
]